# TODO: RUNTIME IS NOT DYNAMIC YET. AT THE MOMENT IT IS HARDCODED TO THE MOST RECENT VERSION SUPPORTED.
name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:src/runtimes/php83"
          push: true
          tags: |
            hoejdk/larapod:php83
            hoejdk/larapod:php8.3${{ github.ref_type == 'tag' && format('-{0}', github.ref_name) || '' }}